/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'Index.ce': typeof import('./src/components/StaffTable/index.ce.vue')['default']
    Row: typeof import('./src/components/StaffTable/Row.vue')['default']
    'SelectField.ce': typeof import('./src/components/SelectField.ce.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    ULinkBase: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
  }
}
